create table app_user (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    created_at timestamp not null
);

create table todo (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    completed boolean not null,
    created_at timestamp not null,
    owner_id bigint not null,
    constraint fk_todo_owner foreign key (owner_id) references app_user(id)
);

create index idx_todo_owner_created_at on todo(owner_id, created_at);
create index idx_todo_owner_completed on todo(owner_id, completed);
